### 더미 채널 등록
POST http://localhost:8080/api/dummyChannel
Content-Type: application/json

{
  "deviceCode": "TEST-DEVICE",
  "channelCode": "TEST-CHANNEL-1",
  "channelTypeId": 0,
  "minValue": 100,
  "maxValue": 200,
  "tenantId": 245,
  "platformCode": "SIMMTECH",
  "cycle": 5,
  "kafkaTopic": "smp"
}

### 더미 채널 삭제
DELETE http://localhost:8080/api/dummyChannel
Content-Type: application/json

{
  "deviceCode": "TEST-DEVICE",
  "channelCode": "TEST-CHANNEL-1",
  "channelTypeId": 0,
  "tenantId": 1,
  "platformCode": "platform01"
}

### 스케쥴러 리스트
GET http://localhost:8080/api/scheduler/count

###
